Release PR

diff --git a/.github/workflows/ci-pr.yml b/.github/workflows/ci-pr.yml
--- a/.github/workflows/ci-pr.yml
+++ b/.github/workflows/ci-pr.yml
@@ -7,13 +7,23 @@ on:
         types: [opened, edited, synchronize, reopened]
         branches:
             - release/*
-            - release/*
-            - release/*
-
+            
 # Jobs to be executed
 jobs:
-    format-lint-lwc-tests:
+    documentacion:
         runs-on: ubuntu-latest
+        steps:
+            - name: 'Checkout source code'
+              uses: actions/checkout@v2
+
+            - name: 'Watch CodeTour changes'
+              uses: pozil/codetour-watch@v1.2.0
+              with:
+                  repo-token: ${{ secrets.GITHUB_TOKEN }}
+
+    formato:
+        runs-on: ubuntu-latest
+        needs: documentacion
         steps:
             # Checkout the source code
             - name: 'Checkout source code'
@@ -43,19 +53,81 @@ jobs:
             - name: 'Lint Lightning Web Components'
               run: npm run lint:lwc
 
+    codigo:
+        name: AnalisisCodigo
+        runs-on: ubuntu-latest
+        needs: formato
+        steps:
+            - uses: actions/checkout@v2
+              with:
+                  # Shallow clones should be disabled for a better relevancy of analysis
+                  fetch-depth: 0
+            - name: Scan
+              uses: SonarSource/sonarcloud-github-action@master
+              env:
+                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+                  # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
+                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+    test:
+        name: TestCodigo
+        runs-on: ubuntu-latest
+        needs: codigo
+        if: ${{ github.actor != 'dependabot[bot]' }}
+        steps:
+            # Install Salesforce CLI
+            - name: 'Install Salesforce CLI'
+              run: |
+                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
+                  mkdir ~/sfdx
+                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
+                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
+                  ~/sfdx/bin/sfdx version
+            # Checkout the source code
+            - name: 'Checkout source code'
+              uses: actions/checkout@v2
+
+            # Store secret for dev hub
+            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
+              shell: bash
+              run: |
+                  echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
+                  secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+                      exit 1;
+                  fi
+            # Authenticate dev hub
+            - name: 'Authenticate Dev Hub'
+              run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d
+
+            # Run Apex tests in scratch org
+            - name: 'Run Apex tests'
+              run: sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20
+
+            # Delete temporary test file that Codecov is unable to parse
+            - name: 'Delete coverage file (temporary step)'
+              run: rm ./tests/apex/test-result-707*-codecoverage.json
+
+            # Upload code coverage data
+            - name: 'Upload code coverage for Apex to Codecov.io'
+              uses: codecov/codecov-action@v2.0.2
+              with:
+                  flags: Apex
+
             # LWC unit tests
             - name: 'Unit test Lightning Web Components'
               run: npm run test:unit:coverage
 
             # Upload code coverage data
             - name: 'Upload code coverage for LWC to Codecov.io'
-              uses: codecov/codecov-action@v1
+              uses: codecov/codecov-action@v2.0.2
               with:
                   flags: LWC
 
-    test-enviroment:
+    despliegue:
         runs-on: ubuntu-latest
-        needs: format-lint-lwc-tests
+        needs: test
         steps:
             # Install Salesforce CLI
             - name: 'Install Salesforce CLI'
@@ -78,39 +150,10 @@ jobs:
             - name: 'Authenticate Dev Hub'
               run: sfdx auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a devhub -d
 
-            # Create scratch org
-            - name: 'Create scratch org'
-              run: sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1
+            # Create deploy task
+            - name: 'deploy in a production org'
+              run: sfdx force:source:deploy --sourcepath force-app/main/default --loglevel fatal -l RunLocalTests
 
-            # Wait for package replication
-            - name: 'Wait for two min for Communities activation'
-              uses: maddox/actions/sleep@master
-              with:
-                  args: 120
-
-            # Deploy source to scratch org
-            - name: 'Push source to scratch org'
-              run: sfdx force:source:push
-
-            # Assign permissionset
-            - name: 'Assign permissionset to default user'
-              run: sfdx force:user:permset:assign -n ebikes
-
-            # Import sample data
-            - name: 'Import sample data'
-              run: sfdx force:data:tree:import -p ./data/sample-data-plan.json
-
-            # Run Apex tests in scratch org
-            - name: 'Run Apex tests'
-              run: sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20
-
-            # Upload code coverage data
-            - name: 'Upload code coverage for Apex to Codecov.io'
-              uses: codecov/codecov-action@v1
-              with:
-                  flags: Apex
-
-            # Housekeeping
-            - name: 'Delete scratch org'
-              if: always()
-              run: sfdx force:org:delete -p -u scratch-org
+            # logout system
+            - name: 'logout system'
+              run: sfdx force:auth:logout -p -u devhub
